openapi: 3.0.1
info:
  title: Hello World API
  description: A sample API to demonstrate authentication and connectivity
  version: "1.0"
servers:
- url: https://dev-api.livestockinformation.org.uk/public/hello-world
- url: https://dev-cla.api.livestockinformation.org.uk/public/hello-world
paths:
  /hello-world:
    get:
      summary: Hello world operation
      description: A demonstration of a GET call on a sample resource.
      operationId: get_hello_world
      parameters:
      - name: param1
        in: query
        description: A sample parameter that is optional and has a default value of
          "sample".
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: sample
          enum:
          - sample
      responses:
        "200":
          description: Returned in all cases.
        "401":
          description: Request could not be authenticated.
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas: {}
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_apiKeyHeader
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_apiKeyQuery

