openapi: 3.0.3
info:
  title: Steam Library API
  description: API for pulling game data from MongoDB
  version: "1.0"
servers:
- url: /app/v1/api
paths:
  /gamesLibrary:
    get:
      summary: Get the entire library
      description: Returns a JSON Object of the user's entire Steam library
      operationId: get_games_library
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/gamesLibrary'
                x-content-type: application/json
        "400":
          $ref: '#/components/schemas/400BadRequestError'
        "404":
          $ref: '#/components/schemas/404NotFoundError'
        "500":
          $ref: '#/components/schemas/500InternalServerError'
      x-openapi-router-controller: swagger_server.controllers.games_get
  /gamesLibrary/{title}:
    get:
      summary: Get a single game
      description: Returns the record of a game in the library
      operationId: get_game
      parameters:
      - name: title
        in: path
        description: The name of a game
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: Hello Kitty Island Adventure
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/game'
                x-content-type: application/json
        "400":
          $ref: '#/components/schemas/400BadRequestError'
        "404":
          $ref: '#/components/schemas/404NotFoundError'
        "500":
          $ref: '#/components/schemas/500InternalServerError'
      x-openapi-router-controller: swagger_server.controllers.games_get
  /gamesLibrary/search/:
    get:
      summary: Get a single game
      description: Returns the record of a game in the library
      operationId: search_game_year
      parameters:
      - name: year
        in: query
        description: The date a game was published
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: "1970"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/game'
                x-content-type: application/json
        "400":
          $ref: '#/components/schemas/400BadRequestError'
        "404":
          $ref: '#/components/schemas/404NotFoundError'
        "500":
          $ref: '#/components/schemas/500InternalServerError'
      x-openapi-router-controller: swagger_server.controllers.games_search
components:
  schemas:
    Error:
      required:
      - detail
      - status
      - title
      - type
      type: object
      properties:
        detail:
          type: string
        status:
          type: integer
        title:
          type: string
        type:
          type: string
    "400BadRequestError":
      description: The request could not be understood by the server
    "404NotFoundError":
      description: The requested resource could not be found on the server
    "500InternalServerError":
      description: The server was unresponsive
    DefaultError:
      description: Unexpected Error
    gamesLibrary:
      allOf:
      - type: object
        properties:
          count:
            type: integer
            description: The total number of games in the library
            readOnly: true
          games:
            type: array
            items:
              $ref: '#/components/schemas/game'
    game:
      type: object
      properties:
        title:
          type: string
          description: The name of the game
          readOnly: true
        genres:
          type: array
          description: The genres to which the game belongs
          readOnly: true
        publishers:
          type: array
          description: The name of the publisher(s)
          readOnly: true
        yearOfPublication:
          type: string
          description: The year the game was published
          readOnly: true
        tags:
          type: array
          description: Custom tags to add to the record for searching
          readOnly: false
      example:
        yearOfPublication: yearOfPublication
        genres: ""
        publishers: ""
        title: title
        tags: ""
  parameters:
    titleParam:
      name: title
      in: path
      description: The name of a game
      required: true
      style: simple
      explode: false
      schema:
        type: string
      example: Hello Kitty Island Adventure
    genresParam:
      name: genres
      in: query
      description: The genres of a game
      required: false
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string
      example: Action
    yearParam:
      name: year
      in: query
      description: The date a game was published
      required: false
      style: form
      explode: true
      schema:
        type: string
      example: "1970"
    dateRangeStartParam:
      name: dateRangeStart
      in: path
      description: The date range a game was published
      required: true
      style: simple
      explode: false
      schema:
        type: string
      example: "1900"
    dateRangeEndParam:
      name: dateRangeEnd
      in: path
      description: The date range a game was published
      required: true
      style: simple
      explode: false
      schema:
        type: string
      example: "1901"
    publisherParam:
      name: publisher
      in: path
      description: The publisher of a game
      required: true
      style: simple
      explode: false
      schema:
        type: array
      example: Contoso

